---
# https://github.com/james-willett/mkdocs-material-youtube-tutorial
# https://mkdocstrings.github.io/recipes/
# site info set in workflow
site_name: '<gha_sed_site_name_here>'
site_description: '<gha_sed_description_here>'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
#  palette:
#    - scheme: default
#      toggle:
#        icon: material/toggle-switch-off-outline 
#        name: Switch to dark mode
#      primary: teal
#      accent: purple 
#    - scheme: slate 
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode    
#      primary: teal
#      accent: lime
nav:
  - Home: index.md
  - PRD: PRD.md
  - Code: docstrings.md
  - Configuration: pyproject.md
  - Change Log: CHANGELOG.md
  - License: LICENSE.md
plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          show_source: false
          heading_level: 2
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
validation:
  links:
    not_found: warn
    anchors: warn
# builds only if validation succeeds while
# threating warnings as errors
# also checks for broken links
# strict: true
...