---
# https://github.com/james-willett/mkdocs-material-youtube-tutorial
# https://mkdocstrings.github.io/recipes/
# site info set in workflow
site_name: '<gha_sed_site_name_here>'
site_description: '<gha_sed_description_here>'
theme:
  name: material
  language: en
  features:
    - content.code.annotation
    - content.code.copy
    - content.code.tabbed
    - content.tabs.link
    - github.edit_on_github
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - user_color_mode_toggle
    - user_font_size_toggle
    - user_theme_toggle
    - toc.integrate
    - search.suggest
    - search.highlight
nav:
  - Home: index.md
  - PRD: PRD.md
  - Code: docstrings.md
  - Change Log: CHANGELOG.md
  - License: LICENSE.md
plugins:
  - search:
      lang: en
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 1
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            docstring_section_style: "table"
markdown_extensions:
  - attr_list
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty
  - toc:
      permalink: true
validation:
  links:
    not_found: warn
    anchors: warn
# builds only if validation succeeds while
# threating warnings as errors
# also checks for broken links
# strict: true
...