---
# https://github.com/callowayproject/bump-my-version?tab=readme-ov-file#github-actions
name: Bump Version with bump-my-version

on:
  pull_request:
    inputs:
      bump_type:
        required: true
        default: minor
        type: string
    branches:
      - main
  push:
    inputs:
      bump_type:
        required: true
        default: patch
        type: string
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@0.28.0
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump_type }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          previous=${{ steps.bump.outputs.previous-version }}
          current=${{ steps.bump.outputs.current-version }}
          echo "Version was bumped from ${previous} to ${current}!"

#      - name: Get new version
#        id: get_version
#        run: echo "new_version=$(cat version.md | tr -d '\n')" >> $GITHUB_OUTPUT

#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: v${{ steps.get_version.outputs.new_version }}
#          release_name: Release ${{ steps.get_version.outputs.new_version }}
#          draft: false
#          prerelease: false
...
