---
name: "bump-my-version"

on:
  # pull_request:
  #  types: [closed]
  #  branches: [main]
  workflow_dispatch:
    inputs:
      bump_type:
        description: '[major|minor|patch]'
        required: true
        default: 'patch'
        type: choice
        options:
        - 'major'
        - 'minor'
        - 'patch'

env:
  BRANCH_NEW: "bump-${{ github.run_number }}-${{ github.ref_name }}"
  SKIP_PR_HINT: "[skip ci bump]"

jobs:
  bump-my-version:
    # TODO bug? currently resulting in: Unrecognized named-value: 'env'.
    # https://stackoverflow.com/questions/61238849/github-actions-if-contains-function-not-working-with-env-variable/61240761
    # if: !contains(
    #      github.event.pull_request.title,
    #      ${{ env.SKIP_PR_HINT }}
    #    )
    # TODO check for PR closed by bot to avoid PR creation loop
    # github.actor != 'github-actions'
    if: >
        github.event_name == 'workflow_dispatch' ||
        ( github.event.pull_request.merged == true &&
        github.event.pull_request.closed_by != 'github-actions' )
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: write
      pull-requests: write
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create new branch
        id: branch
        run: |
          git config user.email "bumped@qte77.gha"
          git config user.name "bump-my-version"
          git checkout -b ${{ env.BRANCH_NEW }}

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@0.29.0
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump_type }}
          branch: ${{ env.BRANCH_NEW }}

      - name: "Create PR '${{ env.BRANCH_NEW }}'"
        if: steps.bump.outputs.bumped == 'true'
        env:
          VER_PREVIOUS: ${{ steps.bump.outputs.previous-version }}
          VER_CURRENT: ${{ steps.bump.outputs.current-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base ${{ github.ref_name }} \
            --head ${{ env.BRANCH_NEW }} \
            --title "PR ${{ env.BRANCH_NEW }} ${{ env.SKIP_PR_HINT }}" \
            --body "PR automatically created from `${{ github.ref_name }}` to bump from `${{ env.VER_PREVIOUS }}` to `${{ env.VER_CURRENT }}` on `${{ env.BRANCH_NEW }}`." \
            # --label "bump"

      - name: Delete branch and PR in case of failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            del_msg="'${{ env.BRANCH_NEW }}' force deletion attempted."
            else_msg="'${{ env.BRANCH_NEW }}' does not exist. Skipping closure."
            pr_msg="Closing PR'${{ env.BRANCH_NEW }}' to rollback after failure"
            echo "PR ${del_msg}."
            gh pr close "${{ env.BRANCH_NEW }}" --comment "${pr_msg}" || \
              echo "PR $else_msg"
            echo "Branch ${del_msg}"
            gh api "repos/${{ github.repository }}/git/refs/heads/${{ env.BRANCH_NEW }}" -X DELETE && echo "Branch deleted" || echo "Branch $else_msg"
  
  generate_summary:
    name: Generate Summary Report 
    if: ${{ !cancelled() }}
    needs: bump-my-version
    uses: "./.github/workflows/summarize-jobs-reusable.yaml"
...