---
name: Generate and deploy MkDocs to GitHub Pages

on:
  push:
  workflow_dispatch:
  
env:
  UV_VER: '0.5.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/configure-pages@v3

    # caching instead of actions/cache@v4
    # https://docs.astral.sh/uv/guides/integration/github/#caching
    - name: Install uv with cache dependency glob
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ env.UV_VER }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    # setup python from pyproject.toml using uv
    # instead of using actions/setup-python@v5
    # https://docs.astral.sh/uv/guides/integration/github/#setting-up-python
    - name: "Set up Python"
      run: uv python install

#    - name: Install only doc deps
#      run: uv sync --only-group docs

    - name: Get repo info and stream into mkdocs.yml
      id: repo_info
      run: |
        REPO_INFO=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }})
        SITE_NAME=$(sed '1!d' README.md | sed '0,/# /{s/# //}')
        SITE_DESC=$(echo $REPO_INFO | jq -r .description)
        sed -i "s/<gha_sed_site_name_here>/${SITE_NAME}/g" mkdocs.yml
        sed -i "s/<gha_sed_description_here>/${SITE_DESC}/g" mkdocs.yml

    - name: Copy repo files
      run: |
        cp README.md docs/index.md
        cp {CHANGELOG,LICENSE}.md docs/
        cp pyproject.toml docs/pyproject.md

    - name: Create docstrings file
      run: |
        cat << EOF > docs/docstrings.md
        # Code Documentation
        
        ::: src
        EOF

    - name: Build documentation
      run: uv run --only-group docs mkdocs build

#    - name: Push to gh-pages
#      run: uv run mkdocs gh-deploy --force

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
...
