---
name: Generate and deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocstrings[python]

    - name: Create mkdocs.yml
      run: |
        cat << EOF > mkdocs.yml
        site_name: Your Project Name
        theme: material
        plugins:
          - search
          - mkdocstrings:
              handlers:
                python:
                  paths: [app]
        nav:
          - Home: index.md
          - License: license.md
          - Third-Party Licenses: licenses.md
          - Project Configuration: pyproject.md
          - PRD: PRD.md
          - FRD: FRD.md
          - DRD: DRD.md
        EOF

    - name: Prepare documentation files
      run: |
        mkdir -p docs
        cp README.md docs/index.md
        cp LICENSE docs/license.md
        cp LICENSES docs/licenses.md
        cp pyproject.toml docs/pyproject.md
        cp doc/PRD.md docs/PRD.md
        cp doc/FRD.md docs/FRD.md
        cp doc/DRD.md docs/DRD.md

    - name: Build documentation
      run: mkdocs build
      
#    - name: Push to gh-pages
#      run: mkdocs gh-deploy --force

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
...
