---
name: Generate and deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocstrings[python]
        
    - name: Get repo info
      id: repo_info
      run: |
        REPO_INFO=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }})
        REPO_NAME=$(echo $REPO_INFO | jq -r .name)
        REPO_DESCRIPTION=$(echo $REPO_INFO | jq -r .description)
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        echo "repo_description=$REPO_DESCRIPTION" >> $GITHUB_OUTPUT

    - name: Create mkdocs.yml
      run: |
        cat << EOF > mkdocs.yml
        site_name: ${{ steps.repo_info.outputs.repo_name }}
        site_description: ${{ steps.repo_info.outputs.repo_description }}
        theme: material
        plugins:
          - search
          - mkdocstrings:
              handlers:
                python:
                  paths:
                    - app
                    - app/utils
        nav:
          - Home: index.md
          - Code: docstrings.md
          - PRD: PRD.md
          - FRD: FRD.md
          - DRD: DRD.md
          - Change Log: CHANGELOG.md
          - License: LICENSE.md
          - Third-Party Licenses: LICENSES.md
        EOF
        #  - Configuration: pyproject.md

    - name: Copy repo files
      run: |
        mkdir -p docs
        cp README.md docs/index.md
        cp CHANGELOG.md docs/CHANGELOG.md
        cp LICENSE docs/LICENSE.md
        cp LICENSES docs/LICENSES.md
        # cp pyproject.toml docs/pyproject.md
        cp doc/PRD.md docs/PRD.md
        cp doc/FRD.md docs/FRD.md
        cp doc/DRD.md docs/DRD.md
        
    - name: Create docstrings file
      run: |
        cat << EOF > docs/docstrings.md
        # Code Documentation
        
        ::: app
        
        ::: app.utils
        EOF

    - name: Build documentation
      run: mkdocs build
      
#    - name: Push to gh-pages
#      run: mkdocs gh-deploy --force

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
...
